# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noisemapper', '0003_auto_20161108_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
