# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noisemapper', '0004_recording_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='device_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
