# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noisemapper', '0005_recording_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='measurement_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='measurement_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
