# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noisemapper', '0007_recording_with_headset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='with_headset',
        ),
        migrations.AddField(
            model_name='recording',
            name='mic_source',
            field=models.CharField(choices=[('internal', 'Internal'), ('headset', 'Headset')], default='internal', max_length=20),
        ),
    ]
